//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source_Control_Final_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tbl_user
    {
        [Key]
        public int UserId { get; set; }
        [Required(ErrorMessage = "Please Enter Name")]
        [CharacterValidation("@!?_{}<>*&^%$#.")]
        public string Name { get; set; }
        [StringLength(60, MinimumLength = 20)]
        [Required]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter EmailId")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please Enter Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        [DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Please Enter Phone no.")]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Contact no.")]
        public string Phone { get; set; }
        public string Profile { get; set; }
        [ValidateImage(ErrorMessage = "Please select a .JPG, .JPEG or .PNG file")]
        public HttpPostedFileBase ImageFile { get; set; }
        [Range(18, 65, ErrorMessage = "Age Must be between 18 to 65")]
        [Required(ErrorMessage = "Please Enter Age")]
        public Nullable<int> Age { get; set; }
    }
}
